"""Build the synthetic threat-scenario images (ClickFix, phishing, RMM, ransomware, clean control).

    python -m tests.fixtures.build_threats [--out test_data] [--only RMM-01 ...]

Writes ``test_data/scenarios/<NAME>.E01`` and ``ground_truth.json``.  Requires WSL (Ubuntu) with ntfs-3g, faketime,
libewf-tools (see tests/fixtures/build_all.py).
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys

from tests.fixtures.build_all import ROOT, wsl, wsl_path
from tests.fixtures.builder import scenario_threats as T


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "test_data"))
    ap.add_argument("--only", nargs="*")
    a = ap.parse_args(argv)
    staging = os.path.join(os.path.abspath(a.out), "staging_threats")
    out = os.path.join(os.path.abspath(a.out), "scenarios")
    os.makedirs(staging, exist_ok=True)
    os.makedirs(out, exist_ok=True)
    builder = wsl_path(os.path.join(ROOT, "tests", "fixtures", "builder", "wsl_build_disk.py"))
    wsl("mkdir -p /root/vestige_build")
    meta = "-C CASE-SCENARIO -D 'Synthetic threat scenario' -e 'Test Examiner' -N 'Generated by tests/fixtures/build_threats.py'"
    for name, build in T.BUILDERS.items():
        if a.only and name not in a.only:
            continue
        print(f"[{name}] staging", flush=True)
        build(staging)
        print(f"[{name}] disk", flush=True)
        wsl(f"python3 {builder} {wsl_path(os.path.join(staging, name))} /root/vestige_build/{name}.raw")
        wsl(f"cd /root/vestige_build && rm -f {name}.E01 && ewfacquire -u -t {name} -c deflate:fast -f encase6 -E {name} "
            f"{meta} -S 0 {name}.raw >/dev/null && cp {name}.E01 {wsl_path(out)}/ && rm -f {name}.raw {name}.E01")
        print(f"[{name}] {os.path.getsize(os.path.join(out, name + '.E01')) / 1e6:.1f} MB", flush=True)
    with open(os.path.join(out, "ground_truth.json"), "w") as fh:
        json.dump({"answers": T.GROUND_TRUTH, "facts": T.FACTS}, fh, indent=1)
    shutil.rmtree(staging, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
