"""Build the synthetic test evidence set.

    python -m tests.fixtures.build_all [--out test_data]

Produces (in ``test_data/evidence``):
    WKSTN-TEST-01.E01 (+ .raw, .vmdk, .vhdx)   source workstation
    HOME-TEST-02.E01..E0n                       second workstation (segmented EWF)
    USB-TEST.dd                                 the removable stick (FAT32, MBR)
and ``test_data/inputs`` with a DLP alert CSV and the reference documents.
Requires WSL (Ubuntu) with: ntfs-3g dosfstools faketime attr libewf-tools qemu-utils.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys

from tests.fixtures.builder import scenario_basic as S

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def wsl_path(p: str) -> str:
    p = os.path.abspath(p).replace("\\", "/")
    return "/mnt/" + p[0].lower() + p[2:]


def wsl(cmd: str) -> str:
    r = subprocess.run(["wsl", "-u", "root", "-e", "bash", "-c", cmd], capture_output=True)
    out = r.stdout.decode(errors="replace").replace("\x00", "")
    if r.returncode != 0:
        raise RuntimeError(out + r.stderr.decode(errors="replace").replace("\x00", ""))
    return out


def inject_slack(raw: str, manifest: dict) -> None:
    """Write marker bytes into the file slack of the given files (post build)."""
    from dissect.ntfs import NTFS
    from dissect.volume.disk import Disk

    with open(raw, "r+b") as fh:
        disk = Disk(fh)
        for vol in disk.partitions:
            fh.seek(vol.offset + 3)
            if fh.read(4) != b"NTFS":
                continue
            fh.seek(0)
            from dissect.util.stream import RangeStream
            fs = NTFS(RangeStream(fh, vol.offset, vol.size))
            cs = fs.cluster_size
            pending = []
            for item in manifest.get("slack", []):
                rec = fs.mft.get(item["path"])
                data_attr = rec.attributes[0x80][0]
                if data_attr.resident:
                    raise ValueError(f"{item['path']} is resident; enlarge it for a slack test")
                runs = list(data_attr.dataruns())
                size = data_attr.header.size
                last_vcn = (size - 1) // cs
                vcn = 0
                lcn = None
                for run_lcn, run_len in runs:
                    if vcn <= last_vcn < vcn + run_len:
                        lcn = run_lcn + (last_vcn - vcn)
                        break
                    vcn += run_len
                tail = size % cs
                data = bytes.fromhex(item["data_hex"])
                if tail == 0 or tail + len(data) > cs:
                    raise ValueError("no room in slack")
                pending.append((vol.offset + lcn * cs + tail + 16, data))
            for off, data in pending:
                fh.seek(off)
                fh.write(data)
                print(f"  slack: wrote {len(data)} bytes at disk offset {off:#x}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "test_data"))
    ap.add_argument("--skip-convert", action="store_true")
    args = ap.parse_args()
    out = os.path.abspath(args.out)
    staging = os.path.join(out, "staging")
    evidence = os.path.join(out, "evidence")
    inputs = os.path.join(out, "inputs")
    docs = os.path.join(inputs, "reference_files")
    for d in (staging, evidence):
        shutil.rmtree(d, ignore_errors=True)
        os.makedirs(d)

    print("[1/5] reference documents")
    hashes = S.make_documents(docs)
    S.write_inputs(inputs, hashes)
    print("[2/5] staging machines")
    machines = [S.build_source(staging, docs), S.build_second(staging, docs)]
    S.build_usb(staging, docs)

    print("[3/5] building disks in WSL")
    builder = wsl_path(os.path.join(ROOT, "tests", "fixtures", "builder", "wsl_build_disk.py"))
    wsl("mkdir -p /root/vestige_build")
    for name in ["WKSTN-TEST-01", "HOME-TEST-02", "USB-TEST"]:
        print("   ", name)
        print("   ", wsl(f"python3 {builder} {wsl_path(os.path.join(staging, name))} /root/vestige_build/{name}.raw").strip())

    print("[4/5] post-processing (slack)")
    for m in machines:
        if not m.manifest.get("slack"):
            continue
        tmp = os.path.join(evidence, m.name + ".raw")
        wsl(f"cp /root/vestige_build/{m.name}.raw {wsl_path(tmp)}")
        inject_slack(tmp, m.manifest)
        wsl(f"cp {wsl_path(tmp)} /root/vestige_build/{m.name}.raw")

    print("[5/5] converting containers")
    e = wsl_path(evidence)
    wsl(f"cp /root/vestige_build/USB-TEST.raw {e}/USB-TEST.dd")
    meta = "-C CASE-TEST-001 -D 'Synthetic test evidence' -e 'Test Examiner' -N 'Generated by tests/fixtures/build_all.py'"
    wsl(f"cd /root/vestige_build && rm -f WKSTN-TEST-01.E01 && ewfacquire -u -t WKSTN-TEST-01 -c deflate:fast -f encase6 "
        f"-E EV-001 {meta} -S 0 WKSTN-TEST-01.raw >/dev/null && cp WKSTN-TEST-01.E01 {e}/")
    wsl(f"cd /root/vestige_build && rm -f HOME-TEST-02.E* && ewfacquire -u -t HOME-TEST-02 -c deflate:fast -f encase6 "
        f"-E EV-002 {meta} -S 5242880 HOME-TEST-02.raw >/dev/null && cp HOME-TEST-02.E0* {e}/")
    if not args.skip_convert:
        wsl(f"cd /root/vestige_build && qemu-img convert -O vmdk WKSTN-TEST-01.raw {e}/WKSTN-TEST-01.vmdk && "
            f"qemu-img convert -O vhdx WKSTN-TEST-01.raw {e}/WKSTN-TEST-01.vhdx")
    for f in sorted(os.listdir(evidence)):
        print(f"    {f:28s} {os.path.getsize(os.path.join(evidence, f)) / 1e6:9.1f} MB")


if __name__ == "__main__":
    sys.exit(main())
